hopefully fix mac problem

diff --git a/files/etc/init.d/freifunk b/files/etc/init.d/freifunk
--- a/files/etc/init.d/freifunk
+++ b/files/etc/init.d/freifunk
@@ -108,6 +108,7 @@ if [ -n "$wifi_device" ]; then
     
     #if not both interfaces work; try only ad-hoc
     if [ -z "$wifi_ap_interface" -o -z "$wifi_ah_interface" ]; then
+      echo "(I) Freifunk: Cannot start ad-hoc and AP mode at the same time - try ad-hoc only now."
       clear_wifi_interfaces
       add_ah_interface
       wifi_restart
@@ -121,39 +122,86 @@ if [ -n "$wifi_device" ]; then
 fi
 
 
-if [ -n "$wifi_ah_interface" ]; then
-    #ad-hoc wifi interface is up
-    bat_interface=$wifi_ah_interface
-    other_interface=$lan_interface
-elif [ -n "$lan_interface" ]; then
-    #lan interface is up
-    bat_interface=$lan_interface
-    other_interface=$wifi_ah_interface
-else
-  echo "(E) Freifunk: No interface for batman found."
-  exit 1
-fi
-echo "(I) Freifunk: interface for batman: '$bat_interface'"
-echo "(I) Freifunk: other interface for batman: '$other_interface'"
+# ------------------------------------- #
+# A S S I G N  I N T E R F A C E S #
+# ------------------------------------- # 
 
-bat_mac=$(ifconfig $bat_interface | grep HWaddr | awk '{print $5}')
-echo "(I) Freifunk: batman interface mac: '$bat_mac'"
+if [ -n "$wifi_ah_interface" ]; then
+    bat_interfaces="$bat_interfaces $wifi_ah_interface"
+fi
+
+if [ -n "$wifi_ap_interface" ]; then
+    mesh_interfaces="$mesh_interfaces $wifi_ap_interface"
+fi
+
+if [ -n "$lan_interface" ]; then
+    if [ -n "$wifi_ah_interface" ]; then
+        mesh_interfaces="$mesh_interfaces $lan_interface"
+    else
+        bat_interfaces="$bat_interfaces $lan_interface"
+    fi
+fi
+
+#trim variables
+trim() { echo $1; }
+bat_interfaces=$(trim "$bat_interfaces")
+mesh_interfaces=$(trim "$mesh_interfaces")
+
+echo "(I) Freifunk: batman-adv interfaces: '$bat_interfaces'"
+echo "(I) Freifunk: mesh interfaces: '$mesh_interfaces'"
+
+if [ -z "$bat_interfaces" ]; then
+    echo "(E) Freifunk: No interface for batman-adv found."
+    exit 1
+fi
+
+
+#use the mac of the first interface used for batman
+mesh_mac=$(ifconfig ${bat_interfaces%% *} | grep HWaddr | awk '{print $5}')
+#translate to locally administered mac address
+a=${mesh_mac%%:*} #cut out first hex
+a=$((0x$a & 253)) #set second bit to 0
+a=`printf '%02x\n' $a` #convert to hex
+mesh_mac="$a:${mesh_mac#*:}" #reassemble mac
+
+echo "(I) Freifunk: mac for mesh: '$mesh_mac'"
+
 
 # ------------------------------------- #
 # C O N F I G U R I N G   N E T W O R K #
 # ------------------------------------- # 
 
 echo "(I) Freifunk: setup /etc/config/network"
+
 uci -q delete network.lan
-uci set network.mesh="interface"
-uci set network.mesh.type="bridge"
-uci set network.mesh.ifname="bat0 $other_interface"
-uci set network.mesh.mtu="1528"
-uci set network.mesh.ipaddr="10.1.1.1"
-uci set network.mesh.macaddr="$bat_mac"
-uci set network.mesh.proto=static
-uci set network.mesh.netmask="255.0.0.0"
-uci -q set network.wan.proto="none" #disable dhcpc on startup
+
+for x in $bat_interfaces; do
+    name=`echo "$x" | tr -d -c a-z0-9_`
+    uci set network.$name="interface"
+    uci set network.$name.ifname=$x
+    #uci set network.$i.mtu=1528 #todo
+    uci set network.$name.proto=none
+    uci set network.$name.auto=1 #bring up the interface at startup
+done
+
+if [ -n "$mesh_interfaces" ]; then
+    uci set network.mesh="interface"
+    uci set network.mesh.type="bridge"
+    uci set network.mesh.ifname="$mesh_interfaces"
+    #uci set network.mesh.mtu="1528"
+    uci set network.mesh.ipaddr="10.1.1.1"
+    uci set network.mesh.macaddr="$mesh_mac"
+    uci set network.mesh.proto=static
+    uci set network.mesh.netmask="255.0.0.0"
+fi
+
+uci -q delete network.wan
+if [ -n "$wan_interface" ]; then
+    uci set network.wan="interface"
+    uci set network.wan.ifname=$wan_interface
+    uci set network.wan.proto="none" #disable dhcpc on startup
+    uci set network.wan.auto=1 #bring up interface
+fi
 
 echo "(I) Freifunk: setup /etc/config/dhcp"
 uci -q delete dhcp.lan
@@ -162,32 +210,43 @@ uci set dhcp.mesh.interface=mesh
 uci set dhcp.mesh.start=$start_ip
 uci set dhcp.mesh.limit=$end_ip
 uci set dhcp.mesh.leasetime=5m #max time for address conflicts
+if [ -z "$wan_interface" ]; then
+    uci -q delete dhcp.wan
+fi
 
 echo "(I) Freifunk: setup /etc/config/firewall"
 while uci -q delete firewall.@forwarding[0]; do :; done #remove lan forwarding
-uci add firewall forwarding
-uci set firewall.@forwarding[-1]="forwarding"
-uci set firewall.@forwarding[-1].src="mesh"
-uci set firewall.@forwarding[-1].dest="wan"
-
 while uci -q delete firewall.@zone[0]; do :; done #remove lan zone
-uci add firewall zone
-uci set firewall.@zone[-1].name=wan
-uci set firewall.@zone[-1].network=wan
-uci set firewall.@zone[-1].input=REJECT
-uci set firewall.@zone[-1].output=ACCEPT
-uci set firewall.@zone[-1].forward=REJECT
-uci set firewall.@zone[-1].masq=1
-uci set firewall.@zone[-1].mtu_fix=1
 
-uci add firewall zone
-uci set firewall.@zone[-1].name=mesh
-uci set firewall.@zone[-1].network=mesh
-uci set firewall.@zone[-1].input=ACCEPT
-uci set firewall.@zone[-1].output=ACCEPT
-uci set firewall.@zone[-1].forward=REJECT
+if [ -n "$wan_interface" ];
+then
+    uci add firewall forwarding
+    uci set firewall.@forwarding[-1]="forwarding"
+    uci set firewall.@forwarding[-1].src="mesh"
+    uci set firewall.@forwarding[-1].dest="wan"
 
-uci set batman-adv.bat0.interfaces="$bat_interface"
+    uci add firewall zone
+    uci set firewall.@zone[-1].name=wan
+    uci set firewall.@zone[-1].network=wan
+    uci set firewall.@zone[-1].input=REJECT
+    uci set firewall.@zone[-1].output=ACCEPT
+    uci set firewall.@zone[-1].forward=REJECT
+    uci set firewall.@zone[-1].masq=1
+    uci set firewall.@zone[-1].mtu_fix=1
+else
+    while uci -q delete firewall.@rule[0]; do :; done
+fi
+
+if [ -n "$mesh_interfaces" ]; then
+    uci add firewall zone
+    uci set firewall.@zone[-1].name=mesh
+    uci set firewall.@zone[-1].network=mesh
+    uci set firewall.@zone[-1].input=ACCEPT
+    uci set firewall.@zone[-1].output=ACCEPT
+    uci set firewall.@zone[-1].forward=REJECT
+fi
+
+uci set batman-adv.bat0.interfaces="$bat_interfaces"
 uci set batman-adv.bat0.gw_mode="client"
 
 
@@ -204,10 +263,15 @@ echo "(I) Freifunk: restart /etc/init.d/firewall"
 echo "(I) Freifunk: restart /etc/init.d/dnsmasq"
 /etc/init.d/dnsmasq restart
 
-ifconfig $bat_interface mtu 1528
-
 echo "(I) Freifunk: restart /etc/init.d/batman-adv"
 /etc/init.d/batman-adv restart
+ifconfig bat0 up #for VirtualBox
+
+#add bat0 to bridge of non-batman interfaces
+#because it does not exist up until now
+if [ -n "$mesh_interfaces" ]; then
+    brctl addif br-mesh bat0
+fi
 
 
 # ------------------------------- #
