implement basic gui access to nodogsplash

diff --git a/files/www/private/cgi-bin/nodogsplash b/files/www/private/cgi-bin/nodogsplash
--- a/files/www/private/cgi-bin/nodogsplash
+++ b/files/www/private/cgi-bin/nodogsplash
@@ -5,26 +5,31 @@ case $POST_func in
   get_status)
     ndsctl status
     ;;
-  clients)
+  get_clients)
     ntsctl clients
     ;;
-  auth)
-    ndsctl auth $POST_mac
-    ;;
-  deauth)
-    ndsctl deauth $POST_mac
-    ;;
-  block)
-    ndsctl block $POST_mac
-    ;;
-  unblock)
-    ndsctl unblock $POST_mac 
-    ;;
-  allow)
-    ndsctl allow $POST_mac
-    ;;
-  unallow)
-    ndsctl unallow $POST_mac                                                                      
+  auth|deauth|block|unblock|allow|unallow)
+    func="$POST_func"
+    macs="$POST_macs"
+    fail=0
+    for mac in $macs; do
+      if [ `echo "$mac" | grep -c -E '^[[:xdigit:]]{1,2}(:[[:xdigit:]]{1,2}){5}$'` -eq 0 ]; then
+        echo "(E) nodogsplash: Invalid MAC: '$mac'."
+        exit
+      fi
+      
+      ndsctl $func $mac &> /dev/null
+      
+      if [ $? != 0 ]; then
+      	fail=$(($fail + 1))
+      fi
+    done
+    
+    if [ $fail -eq 0 ]; then
+      echo "(I) nodogsplash: Alles ok"
+    else
+      echo "(E) nodogsplash: Something went wrong."  
+    fi
     ;;
   *)
     echo "(E) nodogsplash: Invalid command: '$POST_func'"
