new settings gui design; the wireless settings gui part is broken atm.

diff --git a/files/www/private/cgi-bin/settings b/files/www/private/cgi-bin/settings
--- a/files/www/private/cgi-bin/settings
+++ b/files/www/private/cgi-bin/settings
@@ -2,80 +2,89 @@
 content-type: text/plain
 
 <%
-. /www/private/cgi-bin/shared.sh
+. /etc/functions.sh
 
-case $GET_func in
+myforeach()                          
+{
+    local pkg sec opt key val old="$IFS"
+    split() { pkg=${1:4}; sec=$2; opt=$3; }
+    IFS="
+"
+    for line in `env | grep "^GET_$1"`; do   
+        key=${line%%=*}
+        val=${line##*=}
+        IFS="#"; split $key;
+        [ -n "$opt" ] && $2 "$pkg" "$sec" "$opt" "$val"
+    done
+    IFS="$old"
+}
+
+apply()
+{
+    local pkg=$1 stype=$2
+    
+    #remove all section of type $stype
+    delete_sections() { uci -q delete $pkg.$1; }
+    config_load "$pkg"
+    config_foreach delete_sections "$stype"
+    
+    #create new sections as needed
+    add_sections()
+    {
+        [ "$3" != "stype" ] && return
+        msec=`uci -q add $1 $4`
+        eval "section_${1}_${2}=\"$msec\""
+    }
+    myforeach $1 add_sections
+    
+    #fill new sections with options
+    add_options()
+    {
+        [ "$3" == "stype" ] && return
+        eval "msec=\"\$section_${1}_${2}\""
+        uci set -q $1.$msec.$3="$val"
+        [ $? -ne 0 ] && {
+            echo "(E) settings: Error detected - settings not stored - please reboot to restore."
+            exit
+        }
+    }
+    myforeach $1 add_options
+    
+    uci commit "$1"
+    echo "(I) settings: Settings for '$1' successfully applied - please reboot to restore."
+}
+
+
+case "$GET_func" in
     get_settings)
-        export_json "freifunk" "settings"
+        uci -X -P /var/state -q show batman-adv
+        uci -X -P /var/state -q show freifunk
+        uci -X -P /var/state -q show wireless 
+        uci -X -P /var/state -q show network
+        #hack to get most existing interfaces
+        ifnames=`ifconfig -a | grep "^[[:alpha:]]" | cut -d " " -f 1 | tr '\n' ' '`
+        echo "ifconfig.all.interfaces=$ifnames"
+        ;;
+    set_wireless)
+        apply "wireless" "wifi-iface"
     ;;
-    set_settings)
-        #ap_ssid="$GET_ap_ssid"
-        mac="$GET_mac"
-        share_internet="$GET_share_internet"
-        mesh_ifs=$(ssort "$GET_mesh_ifs")
-        bat_ifs=$(ssort "$GET_bat_ifs")
-        wan_ifs=$(ssort "$GET_wan_ifs")
-        lan_ifs=$(ssort "$GET_lan_ifs")
-        config_nets=$(strip $GET_config_nets)
+    set_freifunk)
+        apply "freifunk" "settings"
+    ;;
+    set_network)
+        apply "network" "switch_vlan"
+    ;;
+    set_assignment)
+        add() { eval "append ${4}_ifs \"$3\""; }
+        myforeach "set_mode" add
         
-        #if [ `uci -q get freifunk.settings.ap_ssid` != $ap_ssid ]; then
-        #    if [ ${#ap_ssid} -lt 3 -o ${#ap_ssid} -gt 32 ]; then
-        #        echo "(E) Settings: Invalid Accesspoint name: '$ap_ssid'."
-        #        exit
-        #    fi
-        #   uci -q set freifunk.settings.ap_ssid=$ap_ssid
-        #fi
+        uci -q set uci set batman-adv.bat0.interfaces="$mesh_ifs"
+        uci -q set network.mesh.ifname="$public_ifs"
+        uci -q set network.lan.ifname="$private_ifs"
+        uci -q set network.wan.ifname="${wan_ifs%% *}"
         
-        if [ `uci -q get freifunk.settings.share_internet` != $share_internet ]; then
-            if [ "$share_internet" != "yes" -a "$share_internet" != "no" ]; then
-                echo "(E) Settings: yes/no expected for share_internet."
-                exit
-            fi
-            uci -q set freifunk.settings.share_internet=$share_internet
-        fi
-        
-        if [ `uci -q get freifunk.settings.mac` != $mac ]; then
-            #check if mac format is valid
-            if [ `echo "$mac" | grep -c -E '^[[:xdigit:]]{1,2}(:[[:xdigit:]]{1,2}){5}$'` -eq 0 ]; then
-                echo "(E) Settings: Invalid MAC: '$mac'."
-                exit
-            fi
-
-            #ifconfig dummy_ext hw ether $mac up &> /dev/null
-            #ifconfig dummy_mesh hw ether $mac up &> /dev/null
-            #ifconfig br-mesh hw ether $mac up &> /dev/null
-            #ifconfig br-mesh `/sbin/mac2ip $mac` &> /dev/null
-
-            uci -q set freifunk.settings.mac="$mac"
-        fi
-        
-        [ -z "$config_nets" ] && { echo "(E) Settings: config_nets is empty."; exit; }
-        uci -q set freifunk.settings.config_nets="$config_nets"
-
-        if [ $(count $wan_ifs) -gt 1 ]; then
-            echo "(E) Settings: Multi-WAN is not yet supported."
-            exit
-        fi
-
-        all_ifs=$(ssort "$bat_ifs $mesh_ifs $wan_ifs $lan_ifs")
-        all_ifs_uniq=$(ssort_uniq "$bat_ifs $mesh_ifs $wan_ifs $lan_ifs")
-        if [ "$all_ifs" != "$all_ifs_uniq" ]; then
-            echo "(E) Settings: Duplicate entries detected."
-            exit
-        fi
-
-        #for ifce in $all_ifs; do
-        #    ifconfig $ifce &> /dev/null
-        #    [ $? != 0 ] && { echo "(E) settings: '$ifce' does not exist."; exit; }
-        #done
-
-        uci -q set freifunk.settings.mesh_interfaces="$mesh_ifs "
-        uci -q set freifunk.settings.bat_interfaces="$bat_ifs "
-        uci -q set freifunk.settings.wan_interfaces="$wan_ifs "
-        uci -q set freifunk.settings.lan_interfaces="$lan_ifs "
-        
-        uci commit freifunk
-        echo "(I) Settings: Settings saved. Please reboot to apply changes."
+        uci commit batman-adv
+        uci commit network
     ;;
     *)
         echo "(E) settings: Invalid command: '$GET_func'"
